apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: s1prove
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzMXByb3ZlMTIuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcE1aWFpsYkZWUU9EVXpOQT09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
