apiVersion: v1
kind: Service
metadata:
  name: s1prove-rtp
  namespace: s1prove
spec:
  type: NodePort
  selector:
    app: s1prove-rtp
  ports: 
  - nodePort: 30082
    port: 8000
    targetPort: 8000

